# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [14]:
import numpy as np

# Create a Numpy array of shape (5,5) filled with random integers 
array = np.random.randint(1,21, size = (5,5))
print("Orignal Array:")
print(array)

# Replace all the elements in the third column with 1 
array[:,2]=1
# print(array[:])
print("Modified Array:")
print(array) 

Orignal Array:
[[15  6  7 14  8]
 [ 5 18  5  7 18]
 [ 1 15  3  6 12]
 [ 6  5  8 10  5]
 [ 8 16 13  1 11]]
Modified Array:
[[15  6  1 14  8]
 [ 5 18  1  7 18]
 [ 1 15  1  6 12]
 [ 6  5  1 10  5]
 [ 8 16  1  1 11]]


In [16]:
# Create a Numpy array of shape (4,4) with values from 1 to 16
array = np.arange(1,17).reshape((4,4))  ## The np.arange function in NumPy is used to create arrays
                                         ## .reshape((4,4)) takes the 1D array and rearranges it into a 4x4 matrix
print("Orignal array:")
print(array)

# Replace the disgonal elements with 0
np.fill_diagonal(array, 0)
print("Modified array:")
print(array)

Orignal array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [18]:
# Create a Numpy array of shape (6,6) with values from 1 to 36
array = np.arange(1,37).reshape(6,6)
print("Orignal Value:")
print(array)

# Extract the sub-array
print(array[2:5, 1:4])

Orignal Value:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [ ]:
array = np.random.randint(1,21,size = (5,5))
print("Orignal array:")
print(array)

# Extract the elemenets on the border
print("Modified Array:")
border_elements = np.concatenate((array[0,:], array[-1,:], array[1:-1,0], array[1:-1, -1]))
## We used concatenate to combine all the elements from border and make it an single array
print("Border Elements:")
print(border_elements)

Orignal array:
[[ 7  5  2  9 11]
 [15  3 18  4  2]
 [20  1 16 12  1]
 [ 2  4  4  4 16]
 [ 5  6  2 11 17]]
Modified Array:
Border Elements:
[ 7  5  2  9 11  5  6  2 11 17 15 20  2  2  1 16]


In [34]:
array1 = np.random.randint(1,11, size = (3,4))
array2 = np.random.randint(1,11, size = (3,4))
print('Array 1:')
print(array1)
print("Array 2:")
print(array2)

# Perform element wise operations 
addition = array1 + array2
substraction = array1 - array2
multiplication = array1 * array2
division = array2 / array2

print("Addition")
print(addition)
print("substraction")
print(substraction)
print("Multiplication")
print(multiplication)
print("Division")
print(division)

Array 1:
[[ 8  7  1  1]
 [10  7  3  2]
 [10 10  8 10]]
Array 2:
[[5 5 7 4]
 [1 2 4 9]
 [4 8 2 9]]
Addition
[[13 12  8  5]
 [11  9  7 11]
 [14 18 10 19]]
substraction
[[ 3  2 -6 -3]
 [ 9  5 -1 -7]
 [ 6  2  6  1]]
Multiplication
[[40 35  7  4]
 [10 14 12 18]
 [40 80 16 90]]
Division
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# Create a Numpy array of shape (4,4) with values from 1 to 16

array = np.arange(1,17).reshape((4,4))
print("Orignal array:")
print(array)

# Compute the row-wise and column-wise sum 
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Orignal array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


In [37]:
# Create a Numpy array of shape (5,5) filled with random integers
array = np.random.randint(1,21, size = (5,5))
print("Orignal Array:")
print(array)

## Compute the statistical values 
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:",median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Orignal Array:
[[ 8  7 14  7  2]
 [11 12 15 18 13]
 [20  2  3 19 17]
 [ 7  8  3 16 10]
 [ 4 16  1 10  6]]
Mean: 9.96
Median: 10.0
Standard Deviation: 5.709500853840027
Variance: 32.5984


In [39]:
# Create a Numpy array of shape (3,3) with values from 1 to 9
array = np.arange(1,10).reshape(3,3)
print("Orignal array:")
print(array)

## Normalise the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalised Array:")
print(normalized_array)

Orignal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalised Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [40]:
## Create a NumPy array of shape (3,3) filled with random integers 
array = np.random.randint(1,11,size = (3,3))
row_array = np.random.randint(1,11, size = (3,))
print("Orignal Array:")
print(array)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Resultant array:")
print(result)

Orignal Array:
[[ 3  6 10]
 [ 7 10 10]
 [ 6  9  3]]
1D array:
[3 8 8]
Resultant array:
[[ 6 14 18]
 [10 18 18]
 [ 9 17 11]]


In [2]:
# Create a NumPy array of shape (4,4) filled with random integers 
import numpy as np

array = np.random.randint(1,11, size =(4,4))
column_array = np.random.randint(1,11,size=(4,))
print("Orignal array:")
print(array)
print("1D Array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting 
result = array - column_array[:, np.newaxis]
print("Resulting Array:")
print(result)

Orignal array:
[[ 9  5  2 10]
 [ 9 10  6  5]
 [ 2  6  6  6]
 [ 9  2 10  7]]
1D Array:
[ 3  5 10  9]
Resulting Array:
[[ 6  2 -1  7]
 [ 4  5  1  0]
 [-8 -4 -4 -4]
 [ 0 -7  1 -2]]


In [6]:
# Create a NumPy array of shape (3,3) representing a matrix
matrix = np.random.randint(1,11, size=(3,3))
print("Orignal matrix:")
print(matrix)

#Compute the determinant
Determinant = np.linalg.det(matrix)
print("Determinant:", Determinant) # det_manual = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)

# Compute the inverse 
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues 
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)


Orignal matrix:
[[ 9 10  1]
 [ 2  5  8]
 [ 9  2  6]]
Determinant: 685.0000000000002
Inverse:
[[ 0.02043796 -0.08467153  0.10948905]
 [ 0.08759124  0.06569343 -0.10218978]
 [-0.05985401  0.10510949  0.03649635]]
Eigenvalues: [17.4355584+0.j          1.2822208+6.13542488j  1.2822208-6.13542488j]


In [7]:
# Create two Numpy arrays of shape (2,3) and (3,2)
array1 = np.random.randint(1,11, size =(2,3))
array2 = np.random.randint(1,11, size =(3,2))
print("Array1:")
print(array1)
print("Array2:")
print(array2)

# Perform matrix multiplication 
result = np.dot(array1, array2)
print("Matrix multiplication results:")
print(result)

Array1:
[[ 4 10  1]
 [ 1  7  6]]
Array2:
[[7 9]
 [5 6]
 [9 5]]
Matrix multiplication results:
[[ 87 101]
 [ 96  81]]


In [9]:
# Create a Nunpy array of shape (3,3) with values from 1 to 9
array = np.arange(1,10).reshape((3,3))
print("Orignal array:")
print(array)

# Reshape the array to shape (1,9)
reshaped_array_1 = array.reshape((1,9))
print(reshaped_array_1)

# Reshape the array to shape (9,1)
reshaped_array_2 = reshaped_array_1.reshape((9,1))
print("Reshaped array(9,1):")
print(reshaped_array_2)

Orignal array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
Reshaped array(9,1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [4]:
# Create a Numpy array of shape(5,5) filled with random integers 
import numpy as np
array = np.random.randint(1,21, size = (5,5))
print("Orignal Array")
print(array)

#Flatten the array
flattenned_array = array.flatten()
print("Flattened_Array")
print(flattenned_array)

# Reshape the array back to (5,5)
Reshaped_Array = flattenned_array.reshape(5,5)
print("Reshaped array")
print(Reshaped_Array)

Orignal Array
[[ 7 19  5 11 20]
 [12 13 11 12  2]
 [19  1 13 11  4]
 [ 3 19 17 10  7]
 [12  2 16 11  1]]
Flattened_Array
[ 7 19  5 11 20 12 13 11 12  2 19  1 13 11  4  3 19 17 10  7 12  2 16 11
  1]
Reshaped array
[[ 7 19  5 11 20]
 [12 13 11 12  2]
 [19  1 13 11  4]
 [ 3 19 17 10  7]
 [12  2 16 11  1]]


In [7]:
# Create a NumPy array of shape (5,5) filled with random intergers 

array = np.random.randint(1,21, size=(5,5))
print("Orignal Array")
print(array)

# Use fancy indexing to extract the elements at the corners pf the array 

Corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner Elements")
print(Corners)


Orignal Array
[[ 8  6 13  8  2]
 [ 1  6  1  9 17]
 [20 11 12  3  2]
 [ 1 15  2  2 15]
 [ 2 20  8  7 19]]
Corner Elements
[ 8  2  2 19]


In [8]:
# Create a Numpy array of shape (4,4) filled with random integers 
array = np.random.randint(1,21, size = (4,4))
print("Orignal Array")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10 
array[array > 10] = 10
print("Modified Array:")
print(array)

Orignal Array
[[ 8 10  3 10]
 [20  3  9 14]
 [ 4 18  4 14]
 [11  8  4  5]]
Modified Array:
[[ 8 10  3 10]
 [10  3  9 10]
 [ 4 10  4 10]
 [10  8  4  5]]


In [11]:
# Create a structured array with fields 'Name', 'Age', and 'Weight'
data_type = [('Name', 'U10'), ('Age', 'i4'), ('Weight', 'f4')]
data = np.array([('Shreyash', 25, 55.5), ('Jaspreet', 30, 85.3), ('Robin', 20, 65.2)], dtype= data_type)
print("Orignal array:")
print(data)

# Sort the array by age 
sorted_data = np.sort(data, order = 'Age')
print("Sorted array by age:")
print(sorted_data)

Orignal array:
[('Shreyash', 25, 55.5) ('Jaspreet', 30, 85.3) ('Robin', 20, 65.2)]
Sorted array by age:
[('Robin', 20, 65.2) ('Shreyash', 25, 55.5) ('Jaspreet', 30, 85.3)]


In [ ]:
# Create a structured array with fields 'x' and 'y' 
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Orignal Array:")
print(data)

# Compute the euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis])**2)
print("Euclidean distances:")
print(distances)

# What is broadcasting?	A way to do math on arrays of different shapes automatically.
# Can we subtract without reshaping?	❌ No, not if you want pairwise differences (you’d only get 1D results).
# Why reshape with [:, np.newaxis]?	To convert 1D array into a column vector, enabling 2D subtraction.

# Euclidean Distance = Squareroot((Xi - Xj)**2 + (Yi - Yj)**2)

Orignal Array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[2.         2.82842712 4.47213595]
 [4.47213595 4.         4.47213595]
 [7.21110255 6.32455532 6.        ]]


In [15]:
import numpy.ma as ma

# Create a masked array of shape (4,4) with random integers 
array = np.random.randint(1,21, size=(4,4))
masked_array = ma.masked_greater(array, 10)
print("Orignal Array:")
print(array)
print("Masked Array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Orignal Array:
[[ 8  4 10  7]
 [18 13 14  9]
 [11 11 19 12]
 [ 1 10 13 17]]
Masked Array:
[[8 4 10 7]
 [-- -- -- 9]
 [-- -- -- --]
 [1 10 -- --]]
Sum of unmasked elements: 49


In [17]:
# Create a masked array of shape (3,3) with random integers
array = np.random.randint(1,21, size=(3,3))
masked_array = ma.masked_array(array, mask = np.eye(3, dtype=bool))
print("Orignal Array:")
print(array)
print("Masked Array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements 

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)


Orignal Array:
[[15 11  1]
 [10  4 20]
 [14 12 17]]
Masked Array:
[[-- 11 1]
 [10 -- 20]
 [14 12 --]]
Modified masked array:
[[11 11  1]
 [10 11 20]
 [14 12 11]]
